use std::{path::Path, 
          process::Command};
use regex::Regex;

fn build_prompt(sast: &str, vul: &str, report: &str, project_path: &Path) -> String {
    let prompt = format!(
        "You are a security expert. 
Analyze the following vulnerability report and judge whether the vulnerability is a true positive or a false positive.
This report is generated by {SAST} tool, on vulnerability: {VUL}. Your current work directory is {PWD}.
The report content is as follows:
{REPORT}
You can traverse corresponding project files to analyze the reachability and exploitability of this vul report, and check whether it will
cause a {VUL} vulnerability in the real world, that can be exploited by attackers and cause security risks. 
You should consider the real use scenario of the project, and the actual code logic and data flow (check is there sanitizers), to make your judgment.
Please provide an analysis of the report and a final judgment of whether the vulnerability is a true positive or a false positive.
The final output be exactly one JSON object in a ```json fenced code block, with the following format:
```json
{{
    \"judgement\": \"TP\" or \"FP\", 
    \"analysis\": \"your analysis here\"
}}
```",
        SAST=sast,
        VUL=vul,
        PWD=project_path.display(),
        REPORT=report
    );
    prompt
}

fn extract_final_judgment(response: &str) -> Option<String> {
    let re = Regex::new(r"(?s)```json\s*(.*?)\s*```").ok()?;
    let caps = re.captures(response)?;
    let ret = caps.get(1)?.as_str().to_string();
    let json_obj: serde_json::Value = serde_json::from_str(&ret).ok()?;
    let _judegement = json_obj.get("judgement")?.as_str()?;
    let _analysis = json_obj.get("analysis")?.as_str()?;
    return Some(ret);
}

pub fn run_codex(sast: &str, vul: &str, report: &str, project_path: &Path) -> Result<String, String> {
    let prompt = build_prompt(sast, vul, report, project_path);
    tracing::debug!("Constructed Codex prompt:\n{}", prompt);
    let mut cnt = 0;
    while cnt < 3 {
        cnt += 1;
        let mut cmd = Command::new("codex");
        cmd.arg("exec")
            .arg(&prompt)
            .arg("--skip-git-repo-check")
            .current_dir(project_path);
        tracing::debug!("Executing command: {:?}", cmd);
        let output = cmd.output();
        if let Err(e) = output {
            tracing::error!("Failed to execute codex command: {}", e);
            continue;
        }
        let output = output.unwrap();
        if output.status.success(){
            let response = String::from_utf8_lossy(&output.stdout).to_string();
            let conclusion = extract_final_judgment(&response);
            if let Some(ret) = &conclusion {
                tracing::info!("Extracted Codex conclusion: {}", ret);
                return Ok(ret.to_string());
            }
            else {
                tracing::error!("ERROR FORMAT!!! Failed to extract final judgment from codex response: {}", response);
                continue;
            }
        }else{
            let error_message = String::from_utf8_lossy(&output.stderr).to_string();
            tracing::error!("Codex command failed with error: {}", error_message);
            continue;
        }
    }
    Err("Codex execution failed after 3 attempts".to_string())
    
}