use std::{path::Path, 
          process::Command};
use regex::Regex;

fn build_prompt(sast: &str, vul: &str, report: &str, project_path: &Path) -> String {
    let FP_reasons= "
    A.Limited Context & Dataflow Consctruction:
    A1.Truncated Interprocedural Context: FPs due to shallow or missing project-level dataflow analysis. e.g., the tool only consider a few fucntions, and ignore the project context, and the dataflow is not complete, which lead to false positive.
    A2.Theoretically incorrect control flow: constructs or follows control-flow paths that are theoretically unreachable by static analysis, like paths that are not reachable in call graphs, not considerate the specific values for this reason, all infeasible paths related to the specific values should be considered in Category D or A.
    
    B.Misidentification of Sources or Sinks:
    B1.Incorrect Source/Sink Selection: FPs due to assigning wrong program point as source/sink. Judge only whether the selected source/sink can cause the vulnerability. Do not consider whether the source/sink is reachable; all path- or reachability-related reasons belong in Category D or A.
    
    C.Prompt Misalignment:
    C1.Prompt Deviations:FPs due to LLM not following the prompt or CWE definition properly

    D.Code Semantics Misinterpretation:
    D1.Missed Key Program Points: FPs due to overlooked null-checks, sanitizers, or resource-release points in the reported paths.
    D2.Poor Language-Feature Support: FPs due to misunderstanding the features of Java/C++(constructor, try-with-resources...).
    D3.Path-Insensitive Analysis: FPs due to reporting flows that cannot reach at runtime.
    D4.Type/Structure Blindness: FPs due to ignoring the information of type/structure/class...
    ";

    let sast_to_description = match sast {
        "repoaudit" => "RepoAudit is a repository-level multi-agent framework. It uses an initiator agent to identify security-relevant source values, such as null values for null-pointer-dereference (NPD) detection. An explorer agent then conducts iterative, demand-driven repository exploration by prompting the LLM to analyze one function at a time, with the exploration depth set to three function layers. Finally, a validator agent verifies the explorer's findings from multiple perspectives, including control-flow ordering and the satisfiability of interprocedural path conditions, with path information validated by LLMs.",     

        "knighter" => "Knighter leverages agentic workflow to generate CSA (Clang Static Analyzer) checkers from patch commits. It will first analyze the bug pattern, then generates a high-level plan for implementing the static analyzer. After that, it will iteratively implement the checker, with the help of LLMs to review and fix potential compilation errors. Finally, it will refine the checker based on the feedback from testing on the codebase at the buggy commit and the fixed commit. Then these generated CSA checkers can be used to analyze the codebase and identify potential vulnerabilities.",

        "llmdfa" => "LLMDFA takes a program and its control-flow graph (CFG) as input. For a data-flow analysis task, such as divide-by-zero (DBZ) detection, LLMDFA first extracts sources and sinks by LLM-inferred tree-sitter scripts, which represent the start and end points of the data-flow facts of interest. Given the extracted sources and sinks for a function f, LLMDFA identifies data-flow facts from sources, sinks, return values, and call sites as function summaries, which are then used to construct interprocedural data-flow paths from sources to sinks. For each source-to-sink path, LLMDFA collects the corresponding path condition and validates path feasibility using an LLM or the Z3 solver, ultimately reporting bugs induced by feasible paths.",

        "iris" => "IRIS first leverages CodeQL to extract Internal Function Parameters Candidates and External API candidates, then uses LLM to identify which external APIs is potential sources or sinks, and which internal function parameters are potential sources. Then IRIS combines the LLM-inferred sources/sinks with a predefined CodeQL query tempalte to generate static analysis results to construct potential vulnerable paths. Finally, IRIS uses LLMs to validate the feasibility of the constructed paths and report vulnerabilities induced by feasible paths.",

        "inferroi" => "INFERROI first instructs LLMs to label the involved resource acquisition, release, and reachability validation intentions APIs. The intentions generated by LLMs (which are described in natural language) are then converted into structured expressions. By aggregating these inferred intentions, INFERROI then proceeds to apply a two-stage static analysis algorithm to analyze the control-flow paths extracted from the code. The algorithm first identifies potential leak-risky paths based on the inferred resource acquisition/release APIs, and then prunes leakrisky paths with unreachable resources based on the inferred reachability validation across these paths on sibling branches, so as to reduce false alarms of resource leak detection.",

        "codeql" => "CodeQL first extracts the target program into a code database that represents syntactic, semantic, control-flow, and data-flow facts. Vulnerability detection is then expressed as declarative CodeQL queries over this database. For data-flow or taint-style vulnerabilities, a query typically specifies sources, sinks, sanitizers, and additional flow steps, and CodeQL computes whether data can propagate from a source to a sink through the program representation. A finding is reported when the query conditions are satisfied, often together with a source-to-sink path.",

        "semgrep" => "Semgrep parses source code into structured syntax trees and applies user-provided rules to match security-relevant code patterns. A rule can describe syntactic patterns with metavariables, constraints, and negative patterns, and Semgrep can also perform lightweight semantic and taint-mode analysis by specifying sources, sinks, sanitizers, and propagators. A finding is reported when the code matches the rule pattern or when tainted data is inferred to flow from a source to a sink.",

        "csa" => "Clang Static Analyzer analyzes C/C++ programs during compilation by building Clang's abstract syntax tree and control-flow graph, then performing path-sensitive symbolic execution over possible program paths. Its checkers track abstract program states, such as nullness, memory ownership, allocation status, and constraints over branch conditions. When a checker observes a state that violates its bug condition, such as dereferencing a null pointer or using freed memory, the analyzer reports a warning with a corresponding execution path.",

        "spotbugs" => "SpotBugs analyzes compiled Java bytecode rather than source code. It inspects classes and methods, builds bytecode-level control-flow and data-flow information, and runs a collection of detectors to identify suspicious bug patterns. These detectors reason about facts such as nullness, object usage, type behavior, method calls, and API misuse, and then emit bug instances when the bytecode satisfies a detector's warning condition. For security-focused analyses, SpotBugs is often extended with detectors such as FindSecBugs, which add vulnerability-oriented source/sink and API-misuse checks.",

        "codex" => "Codex approaches vulnerability detection as a code-aware, agentic security review rather than a purely rule-based static analyzer. It builds a repository-specific threat model from the codebase and surrounding context, examines source files and supporting code for plausible broken controls and source-to-sink paths, and then validates candidate findings with targeted checks in an isolated environment to reduce false positives. It ranks findings using reachability, impact, and evidence, can review pull requests or local diffs for security regressions, and can propose focused patches and regression tests for accepted findings. In practice, Codex is best viewed as an AI security reviewer that assists vulnerability discovery, triage, and remediation, with final human review still required.",

        "claudecode" => "ClaudeCode approaches vulnerability detection as a code-aware, agentic security review rather than a purely rule-based static analyzer. It builds a repository-specific threat model from the codebase and surrounding context, examines source files and supporting code for plausible broken controls and source-to-sink paths, and then validates candidate findings with targeted checks in an isolated environment to reduce false positives. It ranks findings using reachability, impact, and evidence, can review pull requests or local diffs for security regressions, and can propose focused patches and regression tests for accepted findings. In practice, Codex is best viewed as an AI security reviewer that assists vulnerability discovery, triage, and remediation, with final human review still required",

        _ => "Unknown SAST tool"
    };
    let prompt = format!(
        "You are a security expert. 
Analyze the following vulnerability report and judge whether the vulnerability is a true positive or a false positive.
This report is generated by {SAST} tool, on vulnerability: {VUL}, the workflow of {SAST} is described as follows: {sast_to_description}
Your current work directory is {PWD}.
The report content is as follows:
{REPORT}
You can traverse corresponding project files to analyze the reachability and exploitability of this vul report, and check whether it will
cause a {VUL} vulnerability in the real world, that can cause the software crash or exploited by attackers and cause security risks. 
You should consider the real use scenario of the project, and the actual code logic and data flow (check is there sanitizers), to make your judgment.
Please provide an analysis of the report and a final judgment of whether the vulnerability is a true positive or a false positive.
The final output be exactly one JSON object in a ```json fenced code block, with the following format:
```json
{{
    \"judgement\": \"TP\" or \"FP\", 
    \"analysis\": \"your analysis here\",
    \"FP_Reason\": [A1, A2,...] (if judgement is FP, list ONE MOST key reason that lead to false positive in this list, if judgement is TP, leave it as an empty list),
    \"evidence\": \"your evidence here, such as code snippets, dataflow paths, or real-world scenarios...\",
    \"new_reason:\": \"if you have new insights and find new reasons that lead to false positives, please also provide the description in this field, or leave this an empty str\"
}}
```

And if the judgement is FP, please provide the ONE MOST key reason in the \"FP_Reason\" field, with evidence to support your judgment in the \"evidence\" field. If the there is no existing reason can explain why the vulnerability is a false positive, but you find new insights and reasons that lead to false positives, please provide your new reason in the \"new_reason\" field.

Your judging process should be as follows:
1.Analyze the report’s source and sink, and check whether the source/sink are correctly identified. In other words, even if the source can reach the sink, would the corresponding vulnerability actually be triggered? This corresponds to Type B1.

2.Analyze the paths involved in the report, and verify whether the current false positive relies on shallow data-flow reasoning or theoretically unreachable control-flow construction, without considering concrete values. This corresponds to Types A1 and A2.

3. If the above conditions are satisfied, determine whether the tool’s analysis error was caused by any of the Type D subcategories.

4. Finally, for LLM-based tools, examine whether the final judgment deviates from the prompt or the target CWE definition, which corresponds to Type C1.

Current FP reaons is as follows:
{FP_reasons}
",
        SAST=sast,
        VUL=vul,
        PWD=project_path.display(),
        REPORT=report
    );
    prompt
}

fn extract_final_judgment(response: &str) -> Option<String> {
    let re = Regex::new(r"(?s)```json\s*(.*?)\s*```").ok()?;
    let caps = re.captures(response)?;
    let ret = caps.get(1)?.as_str().to_string();
    let json_obj: serde_json::Value = serde_json::from_str(&ret).ok()?;
    let _judegement = json_obj.get("judgement")?.as_str()?;
    let _analysis = json_obj.get("analysis")?.as_str()?;
    return Some(ret);
}

pub fn run_codex(sast: &str, vul: &str, report: &str, project_path: &Path) -> Result<String, String> {
    let prompt = build_prompt(sast, vul, report, project_path);
    tracing::info!("Constructed Codex prompt:\n{}", prompt);
    let mut cnt = 0;
    while cnt < 3 {
        cnt += 1;
        let mut cmd = Command::new("codex");
        cmd.arg("exec")
            .arg(&prompt)
            .arg("--skip-git-repo-check")
            .current_dir(project_path);
        tracing::info!("Executing command: {:?}", cmd);
        let output = cmd.output();
        if let Err(e) = output {
            tracing::error!("Failed to execute codex command: {}", e);
            continue;
        }
        let output = output.unwrap();
        if output.status.success(){
            let response = String::from_utf8_lossy(&output.stdout).to_string();
            let conclusion = extract_final_judgment(&response);
            if let Some(ret) = &conclusion {
                tracing::info!("Extracted Codex conclusion: {}", ret);
                return Ok(ret.to_string());
            }
            else {
                tracing::error!("ERROR FORMAT!!! Failed to extract final judgment from codex response: {}", response);
                continue;
            }
        }else{
            let error_message = String::from_utf8_lossy(&output.stderr).to_string();
            tracing::error!("Codex command failed with error: {}", error_message);
            continue;
        }
    }
    Err("Codex execution failed after 3 attempts".to_string())
    
}
